{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "AlticeLabsChallenge API",
    "version" : "1.0.0-SNAPSHOT"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : {
    "/labseq/{number}" : {
      "get" : {
        "tags" : [ "Labseq" ],
        "parameters" : [ {
          "name" : "number",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : { },
    "securitySchemes" : {
      "SecurityScheme" : {
        "type" : "http",
        "description" : "Authentication",
        "scheme" : "basic"
      }
    }
  }
}